'use strict';

module.exports = {
	'STRING': 'String',
	'INTEGER':'Integer',
	'ApplicationTime': 'ApplicationTime',
	'Binary': 'Binary',
	'BinaryArray': 'BinaryArray',
	'Boolean': 'Boolean',
	'CLSID': 'CLSID',
	'CLSIDArray': 'CLSIDArray',
	'Currency': 'Currency',
	'CurrencyArray': 'CurrencyArray',
	'Double': 'Double',
	'DoubleArray': 'DoubleArray',
	'Error': 'Error',
	'Float': 'Float',
	'FloatArray': 'FloatArray',
	'INTEGER_ARRAY': 'IntegerArray',
	'Long': 'Long',
	'LongArray': 'LongArray',
	'Null': 'Null',
	'Object': 'Object',
	'ObjectArray': 'ObjectArray',
	'Short': 'Short',
	'ShortArray': 'ShortArray',
	'SystemTime': 'SystemTime',
	'SystemTimeArray': 'SystemTimeArray',
	'StringArray': 'StringArray'
};
